name: lambda cd

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-northeast-2
      S3_BUCKET_NAME: tfstate-bucket-d8f5bb8d

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: zip lambda domains
        run: |
          mkdir -p dist
          : > dist/lambda-modules.txt

          for dir in domains/*; do
            if [ -d "$dir" ]; then
              name=$(basename "$dir")

              echo "create zip for $name"
              echo "$name" >> dist/lambda-modules.txt

              (
                cd "$dir"

                if [ -d "../../common" ]; then
                  cp -r ../../common ./common
                fi

                zip -r "../../dist/${name}.zip" .
              )
            fi
          done

      - name: deploy to s3
        run: |
          aws s3 cp dist/ s3://${{ env.S3_BUCKET_NAME }}/lambda/ --recursive